services:
  postgres:
    image: postgres:16-alpine
    container_name: triage_postgres
    environment:
      POSTGRES_USER: sre_user
      POSTGRES_PASSWORD: sre_password
      POSTGRES_DB: triage_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sre_user -d triage_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.11
    container_name: triage_redpanda
    command:
      - redpanda start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
      - --mode dev-container
      - --smp 1
    ports:
      - "19092:19092"
      - "8082:8082"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  postgres_data:
  redpanda_data: